language: node_js
node_js:
  - "8"
install:
  - npm install
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run migrate
script:
  - npm run test
#  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/lab --report lcovonly  -- -l  && ./node_modules/.bin/codecov
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost:5432/travis_ci_test
    - JWT_SECRET=averylongjwtsecret
    - JWT_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTIzNCwianRpIjoiYWNmNDAzMTgtZGU2NS00NjM4LThmNGMtOGRjZGJiZDllODJkIiwiaWF0IjoxNTE4MDE4MDg1LCJleHAiOjE1MTgwMjE2ODV9.LtJmUg70x_D_n6tgNYcfYeFS3cjoYRxILLto4KU8WW0
    - errbit_key=xyz
    - errbit_server=http://localhost
